on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    
env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_ANDROID  }}  
  APP_NAME: ${{ 'RN_GHA_APPCENTER_PIPELINE_ANDROID'  }}  
  TESTING_GROUP: ${{  'Tester'  }} 
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-debug.apk'  }}  
  
jobs:
  build:
    name: Deploy Android on AppCenter
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: 'RnGhaAppcenterPipeline'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo from dev branch
        uses: actions/checkout@v2
      - name: Install reactnative-cli
        run: npm install -g react-native-cli
      - name: Install npm dependency
        run: npm install
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        with:
          path: |
           ~/.gradle/caches
           ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
           ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          cd android
          chmod +x gradlew
          ./gradlew assembleDebug
      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false