on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
    
env:
  APP_CENTER_TOKEN: ${{ secrets.APP_CENTER_TOKEN_ANDROID  }}  
  APP_NAME: ${{ 'RN_GHA_APPCENTER_PIPELINE_ANDROID'  }}  
  TESTING_GROUP: ${{  'Tester'  }} 
  UPLOAD_FILE: ${{ 'android/app/build/outputs/apk/app-debug.apk'  }}  
  
jobs:
  build:
    name: Deploy Android on AppCenter
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: 'RnGhaAppcenterPipeline'
    steps:
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout
        uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Install reactnative-cli
        run: npm install -g react-native-cli
      - uses: actions/setup-node@v3
        with:
           node-version: '18'
           cache: 'npm'
           cache-dependency-path: RnGhaAppcenterPipeline/package-lock.json
      - name: Install dependencies
        run: npm install
      - name: Build android
        run: npm run cd android && ./gradlew assembleDebug
      - name: Upload to App Center
        uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: ${{ env.APP_NAME }}
          token: ${{ env.APP_CENTER_TOKEN }}
          group: ${{ env.TESTING_GROUP }}
          file: ${{ env.UPLOAD_FILE }}
          notifyTesters: true
          debug: false