on:
    push:
        branches:
            - 'main'
            - 'feat/*'
    pull_request:
        types:
            - opened
        branches:
            - 'main'
jobs:
    linter:
        name: ESLinter
        runs-on: ubuntu-latest
        steps:
          - name: Cancel previous runs
            uses: styfle/cancel-workflow-action@0.9.1
          - name: Checkout repo from dev branch
            uses: actions/checkout@v2
          - name: Install reactnative-cli
            run: npm install -g react-native-cli
            working-directory: RnGhaAppcenterPipeline
          - uses: actions/setup-node@v3
            with:
              node-version: '18'
              cache: 'npm'
              cache-dependency-path: package-lock.json
          - name: Install npm dependencies
            run: npm install
            working-directory: RnGhaAppcenterPipeline
          - name: Execute lint
            run: npm run lint
            working-directory: RnGhaAppcenterPipeline
    prettier:
        name: Prettier
        runs-on: ubuntu-latest
        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1
            - name: Checkout repo from dev branch
              uses: actions/checkout@v2
            - name: Install reactnative-cli
              run: npm install -g react-native-cli
              working-directory: RnGhaAppcenterPipeline
            - uses: actions/setup-node@v3
              with:
                node-version: '18'
                cache: 'npm'
                cache-dependency-path: package-lock.json
            - name: Install npm dependencies
              run: npm install
              working-directory: RnGhaAppcenterPipeline
            - name: Execute Prettier
              run: |
                npm run format:js
                npm run format:ts
              working-directory: RnGhaAppcenterPipeline
                